#!/bin/bash

# immediately exit if any command being run exits with a non-zero exit code
set -e

# custom logo with big ascii
# create via https://patorjk.com/software/taag/#p=display&f=ANSI%20Regular&t=Inno-DS
echo """

██ ███    ██ ███    ██  ██████        ██████  ███████ 
██ ████   ██ ████   ██ ██    ██       ██   ██ ██      
██ ██ ██  ██ ██ ██  ██ ██    ██ █████ ██   ██ ███████ 
██ ██  ██ ██ ██  ██ ██ ██    ██       ██   ██      ██ 
██ ██   ████ ██   ████  ██████        ██████  ███████ 
                                                    
"""

# will redirect input variables
exec "$@"